[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ipaddress>=1.0.23",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pytz>=2025.2",
    "streamlit>=1.45.0",
    
]
